services:
  mariadb:
    image: mariadb:11.4
    container_name: playmate-db
    environment:
      MARIADB_ROOT_PASSWORD: se26proj_18
      MARIADB_DATABASE: se26proj_18
      MARIADB_USER: se26proj_18
      MARIADB_PASSWORD: se26proj_18
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
