using Microsoft.AspNetCore.Mvc;
using Moq;
using SE26Project_18.Backend.Controllers;
using SE26Project_18.Backend.Models.Dtos;
using SE26Project_18.Backend.Services;

namespace SE26Project_18.Backend.Tests.Controllers;

public class ThinControllerTests
{
    // ==================== GamesController ====================
    [Fact] public async Task Games_GetGames() { var m=new Mock<IGameService>(); m.Setup(s=>s.GetGamesAsync("")).ReturnsAsync(new List<GameDto>()); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).GetGames("")).Result); }
    [Fact] public async Task Games_GetById_Found() { var m=new Mock<IGameService>(); m.Setup(s=>s.GetGameByIdAsync(1)).ReturnsAsync(new GameDto{Id=1,Name="T"}); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).GetGameById(1)).Result); }
    [Fact] public async Task Games_GetById_NotFound() { var m=new Mock<IGameService>(); var r=(await new GamesController(m.Object).GetGameById(99)); var ok=Assert.IsType<OkObjectResult>(r.Result); Assert.Equal(404,Assert.IsType<ApiResponse<GameDto>>(ok.Value).Status); }
    [Fact] public async Task Games_Create() { var m=new Mock<IGameService>(); m.Setup(s=>s.CreateGameAsync(It.IsAny<GameRequestDto>())).ReturnsAsync(new GameDto{Id=1}); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).CreateGame(new GameRequestDto{Name="N"})).Result); }
    [Fact] public async Task Games_Delete_Success() { var m=new Mock<IGameService>(); m.Setup(s=>s.DeleteGameAsync(1)).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).DeleteGame(1)).Result); }
    [Fact] public async Task Games_Delete_NotFound() { var m=new Mock<IGameService>(); m.Setup(s=>s.DeleteGameAsync(99)).ReturnsAsync(false); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).DeleteGame(99)).Result); }
    [Fact] public async Task Games_Update_Success() { var m=new Mock<IGameService>(); m.Setup(s=>s.UpdateGameAsync(1,It.IsAny<GameRequestDto>())).ReturnsAsync(new GameDto{Id=1}); Assert.IsType<OkObjectResult>((await new GamesController(m.Object).UpdateGame(1,new GameRequestDto{Name="X"})).Result); }
    [Fact] public async Task Games_Update_NotFound() { var m=new Mock<IGameService>(); m.Setup(s=>s.UpdateGameAsync(99,It.IsAny<GameRequestDto>())).ThrowsAsync(new KeyNotFoundException()); var r=(await new GamesController(m.Object).UpdateGame(99,new GameRequestDto{Name="X"})); var ok=Assert.IsType<OkObjectResult>(r.Result); Assert.Equal(404,Assert.IsType<ApiResponse<GameDto>>(ok.Value).Status); }

    // ==================== ChatsController ====================
    [Fact] public async Task Chats_GetByUser() { var m=new Mock<IChatService>(); m.Setup(s=>s.GetChatsByUserAsync(1)).ReturnsAsync(new List<ChatBriefDto>()); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).GetChatsByUser(1)).Result); }
    [Fact] public async Task Chats_GetById() { var m=new Mock<IChatService>(); m.Setup(s=>s.GetChatByIdAsync(1,2)).ReturnsAsync(new ChatDto{Id=1}); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).GetChatById(1,2)).Result); }
    [Fact] public async Task Chats_GetById_NotFound() { var m=new Mock<IChatService>(); var r=(await new ChatsController(m.Object).GetChatById(99,1)); var ok=Assert.IsType<OkObjectResult>(r.Result); Assert.Equal(404,Assert.IsType<ApiResponse<ChatDto>>(ok.Value).Status); }
    [Fact] public async Task Chats_GetByUsers() { var m=new Mock<IChatService>(); m.Setup(s=>s.GetChatByUsersAsync(It.IsAny<long[]>())).ReturnsAsync(new ChatDto{Id=1}); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).GetChatByUsers(new[]{1L,2L})).Result); }
    [Fact] public async Task Chats_GetByUsers_Null() { var m=new Mock<IChatService>(); var r=(await new ChatsController(m.Object).GetChatByUsers(new[]{1L,2L})); Assert.IsType<OkObjectResult>(r.Result); }
    [Fact] public async Task Chats_GetByRecruitment() { var m=new Mock<IChatService>(); m.Setup(s=>s.GetChatsByRecruitmentAsync(1)).ReturnsAsync(new List<ChatDto>()); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).GetChatsByRecruitment(1)).Result); }
    [Fact] public async Task Chats_Create() { var m=new Mock<IChatService>(); m.Setup(s=>s.CreateChatAsync(1,1,2)).ReturnsAsync(new ChatDto{Id=1}); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).CreateChat(new CreateChatRequest{RecruitmentId=1,User1Id=1,User2Id=2})).Result); }
    [Fact] public async Task Chats_Create_Throws() { var m=new Mock<IChatService>(); m.Setup(s=>s.CreateChatAsync(99,1,2)).ThrowsAsync(new KeyNotFoundException()); var r=(await new ChatsController(m.Object).CreateChat(new CreateChatRequest{RecruitmentId=99,User1Id=1,User2Id=2})); Assert.Equal(404,Assert.IsType<ApiResponse<ChatDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Chats_Close_Success() { var m=new Mock<IChatService>(); m.Setup(s=>s.CloseChatAsync(1)).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).CloseChat(new IdRequest{Id=1})).Result); }
    [Fact] public async Task Chats_Close_NotFound() { var m=new Mock<IChatService>(); m.Setup(s=>s.CloseChatAsync(99)).ReturnsAsync(false); Assert.IsType<OkObjectResult>((await new ChatsController(m.Object).CloseChat(new IdRequest{Id=99})).Result); }

    // ==================== ResponsesController ====================
    [Fact] public async Task Resp_GetByRecruitment() { var m=new Mock<IResponseService>(); m.Setup(s=>s.GetResponsesByRecruitmentAsync(1)).ReturnsAsync(new List<ResponseDto>()); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).GetResponsesByRecruitment(1)).Result); }
    [Fact] public async Task Resp_GetByUser() { var m=new Mock<IResponseService>(); m.Setup(s=>s.GetResponsesByUserAsync(1)).ReturnsAsync(new List<ResponseDto>()); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).GetResponsesByUser(1)).Result); }
    [Fact] public async Task Resp_Create() { var m=new Mock<IResponseService>(); m.Setup(s=>s.CreateResponseAsync(1,2)).ReturnsAsync(new ResponseDto{Id=1,RecruitmentId=1,ResponserId=2}); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).CreateResponse(new CreateResponseRequest{RecruitmentId=1,ResponserId=2})).Result); }
    [Fact] public async Task Resp_Create_Dup() { var m=new Mock<IResponseService>(); m.Setup(s=>s.CreateResponseAsync(1,2)).ThrowsAsync(new InvalidOperationException("已回应")); var r=(await new ResponsesController(m.Object).CreateResponse(new CreateResponseRequest{RecruitmentId=1,ResponserId=2})); Assert.Equal(409,Assert.IsType<ApiResponse<ResponseDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Resp_Create_NotFound() { var m=new Mock<IResponseService>(); m.Setup(s=>s.CreateResponseAsync(99,2)).ThrowsAsync(new KeyNotFoundException()); var r=(await new ResponsesController(m.Object).CreateResponse(new CreateResponseRequest{RecruitmentId=99,ResponserId=2})); Assert.Equal(404,Assert.IsType<ApiResponse<ResponseDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Resp_Delete() { var m=new Mock<IResponseService>(); m.Setup(s=>s.DeleteResponseAsync(1,"reason")).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).DeleteResponse(new DeleteResponseRequest{Id=1,Reason="reason"})).Result); }
    [Fact] public async Task Resp_Delete_NotFound() { var m=new Mock<IResponseService>(); m.Setup(s=>s.DeleteResponseAsync(99,"r")).ReturnsAsync(false); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).DeleteResponse(new DeleteResponseRequest{Id=99,Reason="r"})).Result); }
    [Fact] public async Task Resp_UpdateStatus_Success() { var m=new Mock<IResponseService>(); m.Setup(s=>s.UpdateResponseStatusAsync(1,"accepted")).ReturnsAsync(new ResponseDto{Id=1}); Assert.IsType<OkObjectResult>((await new ResponsesController(m.Object).UpdateResponseStatus(new UpdateResponseStatusRequest{Id=1,ResponseStatus="accepted"})).Result); }
    [Fact] public async Task Resp_UpdateStatus_NotFound() { var m=new Mock<IResponseService>(); var r=(await new ResponsesController(m.Object).UpdateResponseStatus(new UpdateResponseStatusRequest{Id=99,ResponseStatus="accepted"})); Assert.Equal(404,Assert.IsType<ApiResponse<ResponseDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }

    // ==================== UsersController ====================
    [Fact] public async Task Users_GetById() { var m=new Mock<IUserService>(); m.Setup(s=>s.GetUserByIdAsync(1)).ReturnsAsync(new UserDto{Id=1,Username="u"}); Assert.IsType<OkObjectResult>((await new UsersController(m.Object).GetUserById(1)).Result); }
    [Fact] public async Task Users_GetById_NotFound() { var m=new Mock<IUserService>(); var r=(await new UsersController(m.Object).GetUserById(99)); Assert.Equal(404,Assert.IsType<ApiResponse<UserDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Users_GetAll() { var m=new Mock<IUserService>(); m.Setup(s=>s.GetUsersAsync()).ReturnsAsync(new List<UserDto>()); Assert.IsType<OkObjectResult>((await new UsersController(m.Object).GetUsers()).Result); }
    [Fact] public async Task Users_Update_Success() { var m=new Mock<IUserService>(); m.Setup(s=>s.UpdateUserAsync(1,It.IsAny<Dictionary<string,object>>())).ReturnsAsync(new UserDto{Id=1}); var r=(await new UsersController(m.Object).UpdateUser(new UpdateUserRequest{Id=1,Data=new Dictionary<string,object>{{"nickname","x"}}})); Assert.IsType<OkObjectResult>(r.Result); }
    [Fact] public async Task Users_Update_NotFound() { var m=new Mock<IUserService>(); var r=(await new UsersController(m.Object).UpdateUser(new UpdateUserRequest{Id=99,Data=new Dictionary<string,object>()})); Assert.Equal(404,Assert.IsType<ApiResponse<UserDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }

    // ==================== RecruitmentsController ====================
    [Fact] public async Task Rec_GetRecruitments() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.GetRecruitmentsAsync("",It.IsAny<long[]>(),It.IsAny<long[]>())).ReturnsAsync(new List<RecruitmentDetailDto>()); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitments("",null,null)).Result); }
    [Fact] public async Task Rec_GetByGame() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.GetRecruitmentsByGameAsync(1)).ReturnsAsync(new List<RecruitmentDetailDto>()); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitmentsByGame(1)).Result); }
    [Fact] public async Task Rec_GetById_Found() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.GetRecruitmentByIdAsync(1)).ReturnsAsync(new RecruitmentDetailDto{Id=1,Title="T"}); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitmentById(1)).Result); }
    [Fact] public async Task Rec_GetById_NotFound() { var m=new Mock<IRecruitmentService>(); var r=(await new RecruitmentsController(m.Object).GetRecruitmentById(99)); Assert.Equal(404,Assert.IsType<ApiResponse<RecruitmentDetailDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Rec_GetByChat_Found() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.GetRecruitmentByChatIdAsync(1)).ReturnsAsync(new RecruitmentDetailDto{Id=1}); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitmentByChat(1)).Result); }
    [Fact] public async Task Rec_GetByChat_NotFound() { var m=new Mock<IRecruitmentService>(); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitmentByChat(99)).Result); }
    [Fact] public async Task Rec_GetByPublisher() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.GetRecruitmentsByPublisherIdAsync(1)).ReturnsAsync(new List<RecruitmentDetailDto>()); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).GetRecruitmentsByPublisher(1)).Result); }
    [Fact] public async Task Rec_Create() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.CreateRecruitmentAsync(It.IsAny<RecruitmentDto>())).ReturnsAsync(new RecruitmentDetailDto{Id=1}); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).CreateRecruitment(new RecruitmentDto{Title="T",ExpiredAt="2026-12-31",MaxParticipants=3})).Result); }
    [Fact] public async Task Rec_Create_NotFound() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.CreateRecruitmentAsync(It.IsAny<RecruitmentDto>())).ThrowsAsync(new KeyNotFoundException()); var r=(await new RecruitmentsController(m.Object).CreateRecruitment(new RecruitmentDto{Title="T",ExpiredAt="2026-12-31",MaxParticipants=3})); Assert.Equal(404,Assert.IsType<ApiResponse<RecruitmentDetailDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Rec_Update_Success() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.UpdateRecruitmentAsync(1,It.IsAny<Dictionary<string,object>>())).ReturnsAsync(new RecruitmentDetailDto{Id=1}); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).UpdateRecruitment(new UpdateRecruitmentRequest{Id=1,Data=new Dictionary<string,object>()})).Result); }
    [Fact] public async Task Rec_Update_NotFound() { var m=new Mock<IRecruitmentService>(); var r=(await new RecruitmentsController(m.Object).UpdateRecruitment(new UpdateRecruitmentRequest{Id=99,Data=new Dictionary<string,object>()})); Assert.Equal(404,Assert.IsType<ApiResponse<RecruitmentDetailDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task Rec_Delete_Success() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.DeleteRecruitmentAsync(1)).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).DeleteRecruitment(new IdRequest{Id=1})).Result); }
    [Fact] public async Task Rec_Delete_NotFound() { var m=new Mock<IRecruitmentService>(); m.Setup(s=>s.DeleteRecruitmentAsync(99)).ReturnsAsync(false); Assert.IsType<OkObjectResult>((await new RecruitmentsController(m.Object).DeleteRecruitment(new IdRequest{Id=99})).Result); }

    // ==================== TagsController ====================
    [Fact] public async Task GameTags_GetAll() { var m=new Mock<ITagService>(); m.Setup(s=>s.GetGameTagsAsync()).ReturnsAsync(new List<GameTagDto>()); Assert.IsType<OkObjectResult>((await new GameTagsController(m.Object).GetGameTags()).Result); }
    [Fact] public async Task GameTags_Create() { var m=new Mock<ITagService>(); m.Setup(s=>s.CreateGameTagAsync("R")).ReturnsAsync(new GameTagDto{Id=1,Name="R"}); Assert.IsType<OkObjectResult>((await new GameTagsController(m.Object).CreateGameTag(new CreateTagRequest{Name="R"})).Result); }
    [Fact] public async Task GameTags_Update_Success() { var m=new Mock<ITagService>(); m.Setup(s=>s.UpdateGameTagAsync(1,"R")).ReturnsAsync(new GameTagDto{Id=1,Name="R"}); Assert.IsType<OkObjectResult>((await new GameTagsController(m.Object).UpdateGameTag(1,new CreateTagRequest{Name="R"})).Result); }
    [Fact] public async Task GameTags_Update_NotFound() { var m=new Mock<ITagService>(); var r=(await new GameTagsController(m.Object).UpdateGameTag(99,new CreateTagRequest{Name="X"})); Assert.Equal(404,Assert.IsType<ApiResponse<GameTagDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task GameTags_Delete() { var m=new Mock<ITagService>(); m.Setup(s=>s.DeleteGameTagAsync(1)).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new GameTagsController(m.Object).DeleteGameTag(1)).Result); }
    [Fact] public async Task RecTags_GetAll() { var m=new Mock<ITagService>(); m.Setup(s=>s.GetRecruitmentTagsAsync()).ReturnsAsync(new List<RecruitmentTagDto>()); Assert.IsType<OkObjectResult>((await new RecruitmentTagsController(m.Object).GetRecruitmentTags()).Result); }
    [Fact] public async Task RecTags_Create() { var m=new Mock<ITagService>(); m.Setup(s=>s.CreateRecruitmentTagAsync("C")).ReturnsAsync(new RecruitmentTagDto{Id=1,Name="C"}); Assert.IsType<OkObjectResult>((await new RecruitmentTagsController(m.Object).CreateRecruitmentTag(new CreateTagRequest{Name="C"})).Result); }
    [Fact] public async Task RecTags_Update_Success() { var m=new Mock<ITagService>(); m.Setup(s=>s.UpdateRecruitmentTagAsync(1,"C")).ReturnsAsync(new RecruitmentTagDto{Id=1,Name="C"}); Assert.IsType<OkObjectResult>((await new RecruitmentTagsController(m.Object).UpdateRecruitmentTag(1,new CreateTagRequest{Name="C"})).Result); }
    [Fact] public async Task RecTags_Update_NotFound() { var m=new Mock<ITagService>(); var r=(await new RecruitmentTagsController(m.Object).UpdateRecruitmentTag(99,new CreateTagRequest{Name="X"})); Assert.Equal(404,Assert.IsType<ApiResponse<RecruitmentTagDto>>(Assert.IsType<OkObjectResult>(r.Result).Value).Status); }
    [Fact] public async Task RecTags_Delete() { var m=new Mock<ITagService>(); m.Setup(s=>s.DeleteRecruitmentTagAsync(1)).ReturnsAsync(true); Assert.IsType<OkObjectResult>((await new RecruitmentTagsController(m.Object).DeleteRecruitmentTag(1)).Result); }
}
