// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE26Project_18.Backend.Data;

#nullable disable

namespace SE26Project_18.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727165257_AddJwtAuth")]
    partial class AddJwtAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChatStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NewMessageAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RecruiterId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecruitmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex("ResponserId");

                    b.ToTable("chats");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.GameTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("game_tags");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Recruitment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PublisherId");

                    b.ToTable("recruitments");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.RecruitmentTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("recruitment_tags");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TokenHashed")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHashed")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Response", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RecruitmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int");

                    b.Property<long>("ResponserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex("ResponserId");

                    b.ToTable("responses");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("game_game_tags", b =>
                {
                    b.Property<long>("game_id")
                        .HasColumnType("bigint");

                    b.Property<long>("game_tag_id")
                        .HasColumnType("bigint");

                    b.HasKey("game_id", "game_tag_id");

                    b.HasIndex("game_tag_id");

                    b.ToTable("game_game_tags");
                });

            modelBuilder.Entity("recruitment_game_tags", b =>
                {
                    b.Property<long>("game_tag_id")
                        .HasColumnType("bigint");

                    b.Property<long>("recruitment_id")
                        .HasColumnType("bigint");

                    b.HasKey("game_tag_id", "recruitment_id");

                    b.HasIndex("recruitment_id");

                    b.ToTable("recruitment_game_tags");
                });

            modelBuilder.Entity("recruitment_recruitment_tags", b =>
                {
                    b.Property<long>("recruitment_id")
                        .HasColumnType("bigint");

                    b.Property<long>("recruitment_tag_id")
                        .HasColumnType("bigint");

                    b.HasKey("recruitment_id", "recruitment_tag_id");

                    b.HasIndex("recruitment_tag_id");

                    b.ToTable("recruitment_recruitment_tags");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Chat", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Recruiter")
                        .WithMany("Chats")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.Recruitment", "Recruitment")
                        .WithMany("Chats")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Responser")
                        .WithMany()
                        .HasForeignKey("ResponserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recruiter");

                    b.Navigation("Recruitment");

                    b.Navigation("Responser");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Message", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Recruitment", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Publisher")
                        .WithMany("Recruitments")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Response", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.Recruitment", "Recruitment")
                        .WithMany("Responses")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.User", "Responser")
                        .WithMany("SentResponses")
                        .HasForeignKey("ResponserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recruitment");

                    b.Navigation("Responser");
                });

            modelBuilder.Entity("game_game_tags", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.GameTag", null)
                        .WithMany()
                        .HasForeignKey("game_tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recruitment_game_tags", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.GameTag", null)
                        .WithMany()
                        .HasForeignKey("game_tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.Recruitment", null)
                        .WithMany()
                        .HasForeignKey("recruitment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recruitment_recruitment_tags", b =>
                {
                    b.HasOne("SE26Project_18.Backend.Models.Entities.Recruitment", null)
                        .WithMany()
                        .HasForeignKey("recruitment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE26Project_18.Backend.Models.Entities.RecruitmentTag", null)
                        .WithMany()
                        .HasForeignKey("recruitment_tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.Recruitment", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("SE26Project_18.Backend.Models.Entities.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Recruitments");

                    b.Navigation("SentResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
